name: "Publish"
on:
  release:
    types: [published]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Change version for AMO"
        run: |
          jq '.version = (.version + "m")' src/manifest.json > tmp.json
          mv tmp.json src/manifest.json

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: build
          source: src
          ignoreFiles: '[ ".gitignore" ]'

      - name: "web-ext sign AMO"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed
          releaseNotes: ${{ github.event.release.body }}
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000
